---
  # Connection settings for Telegram
  telegram_log:
    active: True
    token: '5041788603:AAE36ekkRQ2rnR_JSHpmXCieZU-Tg9LxlFY'
    chatid: '599776595'
    

  time_intervals:
    
    # Default (minutes): 10
    send_heroes_for_work: 50

    # Default (minutes): 3
    refresh_heroes_positions: 5

    # Default (seconds): 5
    check_for_new_map_button: 5

    # Default (minutes): 5
    check_for_login: 5

    # Default (seconds): 1
    interval_between_movements: 1
    
    # Intervalo de tempo para verificar se o saldo aumentou
    # Default (minutes): 60
    get_balance: 60

  threshold:
    # Default: 0.7
    default: 0.7

    # Default: 0.8
    common: 0.8

    # Default: 0.8
    rare: 0.8

    # Default: 0.8
    super_rare: 0.8
        
    # Default: 0.8
    epic: 0.8
    
    # Default: 0.8
    legend: 0.8    
    
    # Default: 0.8
    super_legend: 0.8      
    
    # Default: 0.8
    select_wallet_buttons: 0.8

    # Default: 0.9
    go_to_work_btn: 0.9
    
    # Default: 0.7
    bau_roxo: 0.7

    # Default: 0.8
    bau_roxo_50: 0.8

    # Default: 0.7
    bau_gold: 0.7

    # Default: 0.8
    bau_gold_50: 0.8

    # Default: 0.7
    bau_blue: 0.7

    # Default: 0.8
    bau_blue_50: 0.8

    # Default: 0.9
    green_bar: 0.9

  # home mode settings
  home:
    enable: False
    hero_threshold: 0.8
    home_button_threshold: 0.9


  # Default: 60
  scroll_size: 60

  # Default: 5
  scroll_attempts: 5

  # Default: true
  use_click_and_drag_instead_of_scroll: true

  # Default: 200
  click_and_drag_amount: 200

  # Default: green
  # all = use the send all command
  # green = select heroes with green stamina bar (half or full)
  # full = select only heroes with full stamina bar
  select_heroes_mode: "green"


  save_log_to_file: True
